apiVersion: v1
kind: ConfigMap
metadata:
  name: user-manifest-openshift-cli-client
data:
  data: |
    apiVersion: oauth.openshift.io/v1
    grantMethod: auto
    kind: OAuthClient
    metadata:
      name: openshift-cli-client
    redirectURIs:
    - http://127.0.0.1/callback
    - http://[::1]/callback
