apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
  name: cluster
{{ if .ExtraFeatureGates }}spec:
  featureSet: CustomNoUpgrade
  customNoUpgrade:
{{ if .ExtraFeatureGatesEnabled }}{{ printf "%s\n" "    enabled:" }}
{{- range $featureGateEnabled := .ExtraFeatureGatesEnabled }}{{ printf "%s %s\n" "    -" $featureGateEnabled }}{{- end -}}
{{- end -}}
{{ if .ExtraFeatureGatesDisabled }}{{ printf "%s\n" "    disabled:" }}
{{- range $featureGateDisabled := .ExtraFeatureGatesDisabled }}{{ printf "%s %s\n" "    -" $featureGateDisabled }}{{- end -}}
{{- end -}}
{{ else }}spec: {}
{{- end -}}
