apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-apiserver-egress-config
data:
  egress-config.yaml: |
      apiVersion: apiserver.k8s.io/v1beta1
      kind: EgressSelectorConfiguration
      egressSelections:
      - name: controlplane
        connection:
          proxyProtocol: Direct
      - name: etcd
        connection:
          proxyProtocol: Direct
      - name: cluster
        connection:
          proxyProtocol: HTTPConnect
          transport:
            TCP:
              URL: https://konnectivity-server-local.master-{{ .ClusterID }}.svc:{{ .KonnectivityServerClusterPort }}
              TLSConfig:
                CABundle: /etc/kubernetes/secret/ca.crt
                ClientKey: /etc/kubernetes/secret/konnectivity-client.key
                ClientCert: /etc/kubernetes/secret/konnectivity-client.crt
